### ISSUE TITLE
Viewer vs origin

### ISSUE THREAD

**Issue by pcolmer** [marksteele/edge-rewrite#1]
The README says:

    This function is designed to run on the viewer request phase of Lambda@Edge.

In testing, I think it also works with `origin request` ... unless you know of a reason why it shouldn't be used with that? My preference would be to use `origin request` because CloudFront then caches the result, whereas `viewer request` causes the script to run on **every** browser request.

**Comment by marksteele** [comment]
It _should_ work on origin requests too, and yes, it will cache the responses.

The code isn't using any of the origin information being sent in the origin request, so there could be new features here to use this code to rewrite origin info.

Pull requests are welcome :)
