### ISSUE TITLE
load rules from S3

### ISSUE THREAD

**Issue by hmoffatt** [marksteele/edge-rewrite#5]
It would be cool if the rules file could be loaded from S3 rather than packaged with the function. Then the rules could be updated easily.

There are some ideas like this in the AWS blog: https://aws.amazon.com/blogs/networking-and-content-delivery/leveraging-external-data-in-lambdaedge/

**Comment by marksteele** [comment]
I didn't realize when I wrote this that the lambdas would stick around for a while inside cloudfront.

So for a heavily utilized set of rules, it would definitely be easier to update if the rules were stored in S3. The flip side is that it'll be slower when the lambda isn't hot.

 It would be pretty easy to add this.

**Comment by hmoffatt** [comment]
You would probably want to reload them every hour or so (if the lambda lives that long), in case they are changed. But not load them on every request as that would be slow and expensive.

**Comment by marksteele** [comment]
Done. Can now load from URL, see README

**Comment by hmoffatt** [comment]
Thanks. But I would like to get the rules from S3, rather than an arbitrary URL...

I can point it at the same cloudfront distribution but then I might get infinite recursion, as the Lambda will be invoked again to fetch the rules, and so on. The Lambda could specifically ignore a request to fetch the rules file I guess.

**Comment by marksteele** [comment]
Not to be captain obvious here but... S3 is an HTTP API.

You can store the rules on S3 and expose that via a public URL.  Want even more fun? Expose it via CloudFront with an S3 origin that's restricted to only serve things via CloudFront. The possibilities are endless!

Or throw it in an s3 bucket and make the object public.

The other option, which is to use the S3 api would require hardcoding credentials into the Lambda, which is pretty meh. Feel free to fork the code and implement that if you want to.

**Comment by hmoffatt** [comment]
S3 has an HTTP server but I don't want to expose that. I am using S3 as my origin, which uses the native S3 API. Yes you could point it at a CloudFront URL, but if it was the same CloudFront as the edge-rewrite Lambda is used on you'd have to be careful to avoid infinite recursion.

The AWS blog article I linked actually has an example of fetching from S3. It looks like you just need to ensure the role the Lambda runs as has access to the bucket - no need to hardcode credentials.

The lambda event structure includes a bunch of information about the origin, be it S3 or custom (HTTP/HTTPS server). You could actually just infer the rules URL from that. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html

When I get time I'll have a look at it. Thanks for the comments.

**Comment by marksteele** [comment]
So you can update the serveless.yml file and add the needed IAM policy (like this: https://stackoverflow.com/questions/54083185/how-access-s3-bucket-object-in-cloudfront-lambdaedge-function)

Then you'd need to include the s3 sdk into the function and change the http fetch to an S3 call. 

Honestly trying to hide the rewrite rules doesn't really accomplish that much, they can be deduced by client behavior for the most part. YMMV

**Comment by hmoffatt** [comment]
Yeah I'm not concerned about hiding the rewrite rules (by not exposing the static S3 site), it's the rest of the bucket. I'll think it over as that probably isn't really a big deal either.
