### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by treinacloud** [marksteele/edge-rewrite#6]
I have this problem accessing the urls of my endpoint:

I did it the same way as in the documentation.

Any path from my url shows this error

![Annotation 2019-10-25 095937](https://user-images.githubusercontent.com/52660631/67558076-31494900-f70e-11e9-8118-617833cc541b.png)

502 ERROR
The request could not be satisfied.
The Lambda function result failed validation: The specified URI is in an invalid format. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: pf-PMAWpeK6TIPWIP0x1s36w4thsRVHtMOXqZTSVwQbakDC9WTXusg==

**Comment by marksteele** [comment]
There's not really enough information in here to action on.
